### ISSUE TITLE
Consolidation

### ISSUE THREAD

**Issue by lehitoskin** [jeapostrophe/openal#1]
There has already been an OpenAL wrapper for Racket made by `gcr`. It hasn't been touched in years, and that wrapper did not include the functions for recording audio, but it is more or less complete. In my own repository I tracked down those functions and added them.

https://github.com/gcr/racket-audio-experiments
https://github.com/lehitoskin/libopenal-racket

I'm not going to say you cannot still make your own wrapper or that you shouldn't, but in the interest of consolidating manpower on something like this, perhaps you could fork from one of the existing projects.

**Comment by jeapostrophe** [comment]
I wrote mine in 2011, I'm just moving it from get-bonus into its own package:

https://github.com/get-bonus/get-bonus/blob/83b77127d9aabfb3a341432fc1039f728c1e7881/exp/openal.rkt

Your packages are not on http://pkgs.racket-lang.org either, so I didn't know they existed.

This library hasn't been touched by me in almost 3 three years, so I don't anticipate changing it (it already works with what I use it for), but if yours is better, I'm very cool promoting it and if I ever need anything to adopt it.
